In [13]:
import numpy as np

x_data = np.array([1, 2, 3, 4, 5]).reshape(5,1)
t_data = np.array([2, 3, 4, 5, 6]).reshape(5,1) 
print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (5, 1) , t_data.shape =  (5, 1)


In [14]:
raw_data = [ [1, 2], [2, 3], [3, 4], [4, 5], [5, 6] ]

In [15]:
type(raw_data)

list

In [16]:
raw_data=np.array(raw_data)
print(type(raw_data))
print(raw_data[:,:1])
print(raw_data[:,-1:])
print(raw_data[:,:1].shape)
print(raw_data[:,-1:].shape)

<class 'numpy.ndarray'>
[[1]
 [2]
 [3]
 [4]
 [5]]
[[2]
 [3]
 [4]
 [5]
 [6]]
(5, 1)
(5, 1)


In [17]:
W = np.random.rand(1,1)  
b = np.random.rand(1)  
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)
print(W.ndim, b.ndim)

W =  [[0.51921424]] , W.shape =  (1, 1) , b =  [0.89671562] , b.shape =  (1,)
2 1


In [18]:
def loss_func(x, t):
    y = np.dot(x,W) + b
    
    return ( np.sum( (t - y)**2 ) ) / ( len(x) )

In [19]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [20]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x, t):
    y = np.dot(x,W) + b
    
    return ( np.sum( (t - y)**2 ) ) / ( len(x) )

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type
def predict(x):
    y = np.dot(x,W) + b
    
    return y

In [21]:
learning_rate = 1e-2  # 발산하는 경우, 1e-3 ~ 1e-6 등으로 바꾸어서 실행

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, ", b = ", b )

for step in  range(8001):  
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 500 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial error value =  2.8513179950045187 Initial W =  [[0.51921424]] , b =  [0.89671562]
step =  0 error value =  1.6775487391719746 W =  [[0.63118417]] , b =  [0.92091026]
step =  500 error value =  1.9430833880891866e-09 W =  [[0.99997138]] , b =  [1.00010332]
step =  1000 error value =  6.231141153871308e-11 W =  [[0.99999487]] , b =  [1.0000185]
step =  1500 error value =  1.9982220167495316e-12 W =  [[0.99999908]] , b =  [1.00000331]
step =  2000 error value =  6.407961477020201e-14 W =  [[0.99999984]] , b =  [1.00000059]
step =  2500 error value =  2.05492534179119e-15 W =  [[0.99999997]] , b =  [1.00000011]
step =  3000 error value =  6.589800401673169e-17 W =  [[0.99999999]] , b =  [1.00000002]
step =  3500 error value =  2.113239588633766e-18 W =  [[1.]] , b =  [1.]
step =  4000 error value =  6.776819033772658e-20 W =  [[1.]] , b =  [1.]
step =  4500 error value =  2.173198653875139e-21 W =  [[1.]] , b =  [1.]
step =  5000 error value =  6.969249380238854e-23 W =  [[1.]] , b

In [22]:
predict(56) 

array([[57.]])