In [2]:
# x_data = (예습시간, 복습시간)
# t_data = 1 (Pass), 0 (Fail)

import numpy as np
loaded_data = np.loadtxt('./c_data.csv', delimiter=',', dtype=np.float32)
x_data = loaded_data[:,:-1]
t_data = loaded_data[:,-1:]

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape) 

x_data.ndim =  2 , x_data.shape =  (9, 2)
t_data.ndim =  2 , t_data.shape =  (9, 1)


In [3]:
W = np.random.rand(2, 1)  # 2X1 행렬
b = np.random.rand(1)  
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.82057428]
 [0.43500363]] , W.shape =  (2, 1) , b =  [0.41644688] , b.shape =  (1,)


In [4]:
# classification 이므로 출력함수로 sigmoid 정의

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [5]:
# 최종출력은 y = sigmoid(Wx+b) 이며, 손실함수는 cross-entropy 로 나타냄

def loss_func(x, t):
    
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) )  

In [6]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [7]:
def error_val(x, t):
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) )  

def predict(x):
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1  # True
    else:
        result = 0  # False
    
    return y, result

In [9]:
learning_rate = 1e-2  # 1e-2, 1e-3 은 손실함수 값 발산

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W.tolist(),  ", b = ", b )

for step in  range(80001):  
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W.tolist(), ", b = ",b )

Initial error value =  0.07314086647028328 Initial W =  [[2.2821824734871616], [1.0631330620686974]] , b =  [-26.83248368]
step =  0 error value =  0.07314000050173985 W =  [[2.2821894968992074], [1.0631379850703508]] , b =  [-26.83257637]
step =  400 error value =  0.07279524071413271 W =  [[2.284992345103083], [1.0651024000873521]] , b =  [-26.86956642]
step =  800 error value =  0.07245369785876155 W =  [[2.287782272015271], [1.0670573288263285]] , b =  [-26.90638344]
step =  1200 error value =  0.072115327304688 W =  [[2.290559395400139], [1.0690028618748229]] , b =  [-26.94302902]
step =  1600 error value =  0.07178008524013399 W =  [[2.293323831428565], [1.070939088534425]] , b =  [-26.97950475]
step =  2000 error value =  0.07144792865381197 W =  [[2.2960756947053085], [1.0728660968445332]] , b =  [-27.01581218]
step =  2400 error value =  0.07111881531676426 W =  [[2.2988150982986517], [1.0747839736061853]] , b =  [-27.05195285]
step =  2800 error value =  0.07079270376473219 W

In [10]:
test_data = np.array([3, 17]) # (예습, 복습) = (3, 17) => Fail (0)
predict(test_data) 

(array([0.21934317]), 0)

In [11]:
test_data = np.array([5, 8]) # (예습, 복습) = (5, 8) => Fail (0)

predict(test_data) 

(array([0.00035152]), 0)

In [12]:
test_data = np.array([7, 21]) # (예습, 복습) = (7, 21) => Pass (1)

predict(test_data) 

(array([0.99999963]), 1)

In [13]:
test_data = np.array([12, 0])  # (예습, 복습) = (12, 0) => Pass (1)

predict(test_data) 

(array([0.52458558]), 1)