In [4]:
import numpy as np

loaded_data = np.loadtxt('./data-01.csv', delimiter=',', dtype=np.float32)
print(type(loaded_data))
print(loaded_data)

<class 'numpy.ndarray'>
[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [1]:
x_data = loaded_data[ :, 0:-1]
t_data = loaded_data[ :, [-1]]

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape) 

x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)


In [9]:
loaded_data

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [10]:
W = np.random.rand(3,1)  # 3X1 행렬
b = np.random.rand(1)  
print("W = ", W.tolist(), ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.8479170489988567], [0.6193917096677162], [0.661892346442048]] , W.shape =  (3, 1) , b =  [0.31790806] , b.shape =  (1,)


In [11]:
def loss_func(x, t):
    y = np.dot(x,W) + b
    
    return ( np.sum( (t - y)**2 ) ) / ( len(x) )

In [12]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [13]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x, t):
    y = np.dot(x,W) + b
    
    return ( np.sum( (t - y)**2 ) ) / ( len(x) )

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type
def predict(x):
    y = np.dot(x,W) + b
    
    return y

In [14]:
learning_rate = 1e-5  # 1e-2, 1e-3 은 손실함수 값 발산

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data),'\t', " Initial W = ", W.tolist(),'\t', " b = ", b)

for step in  range(10000001):  
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 100000 == 0):
        print("step = ", step,'\t', "error value = ", error_val(x_data, t_data),'\t', "W = ", W.tolist(),'\t', " b = ",b )

Initial error value =  86.32165844783518 	  Initial W =  [[0.8479170489988567], [0.6193917096677162], [0.661892346442048]] 	  b =  [0.31790806]
step =  0 	 error value =  40.470226108764 	 W =  [[0.8341707396535446], [0.6056181644959182], [0.6480515187273955]] 	  b =  [0.31780509]
step =  100000 	 error value =  6.125173439796632 	 W =  [[0.35598606555286105], [0.5299388442732258], [1.1257219980740958]] 	  b =  [0.14591229]
step =  200000 	 error value =  6.096420350688126 	 W =  [[0.3559842555427805], [0.5304147308976678], [1.1273003114491391]] 	  b =  [-0.02363823]
step =  300000 	 error value =  6.069801520916444 	 W =  [[0.3559825140096585], [0.530872615162992], [1.1288189186694344]] 	  b =  [-0.18677481]
step =  400000 	 error value =  6.045158530532397 	 W =  [[0.3559808383571361], [0.5313131780852006], [1.130280078366861]] 	  b =  [-0.34374008]
step =  500000 	 error value =  6.022344718645148 	 W =  [[0.3559792260929731], [0.5317370749148533], [1.13168596372874]] 	  b =  [-0.49

In [46]:
test_data = np.array([100, 98, 81])

predict(test_data) 

array([178.86235518])